spring:
  profiles:
    active: local  # 默认使用本地配置
  application:
    name: GigaChat
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB      # 单个文件最大10MB
      max-request-size: 20MB   # 请求最大20MB

server:
  port: 8123
  servlet:
    context-path: /api
  forward-headers-strategy: framework
  # 添加Tomcat配置
  tomcat:
    remoteip:
      remote-ip-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto
      port-header: X-Forwarded-Port
      host-header: X-Forwarded-Host
      internal-proxies: 127\\.0\\.0\\.1
    # 设置Tomcat的文件上传限制
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ince.gigalike.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# 日志配置
logging:
  level:
    root: INFO
    com.ince.inceaiagent: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug

