# 本地开发环境配置
# 注意：此文件不会被提交到git仓库
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.134.56.239:3306/gigalikedb?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: inceCheng
    password: YEpYGLpRGwn2pNJG
    # Druid specific configurations (optional, Spring Boot auto-configures most)
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  data:
    # Redis 配置
    redis:
      database: 0
      host: localhost
      timeout: 5000
      port: 6379
  session:
    store-type: redis # 明确指定存储类型为 Redis
    timeout: 2592000s # 设置会话超时时间为 30 天 (2592000 秒)


# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
